# Generated by Django 3.2.4 on 2021-06-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('albumId', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('thumbnailUrl', models.CharField(max_length=100, verbose_name=' thumbnailUrl')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
    ]
