# Generated by Django 3.2.4 on 2021-06-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210603_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default=1, max_length=100, verbose_name='url'),
            preserve_default=False,
        ),
    ]
