# Generated by Django 3.2.4 on 2021-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210604_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.CharField(max_length=100, verbose_name='thumbnailUrl'),
        ),
    ]
